---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - 'prettier'

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true

extends:
  - 'eslint:recommended'
  # - 'airbnb-base'  
  - 'prettier'
  

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-unused-vars: "warn"
  # prettier/prettier: 'error'

